### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Almesaody** [Almesaody/Discord-Bot#26]
i start bot and this error [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#".] {
code: 'ERR_UNHANDLED_REJECTION'

**Comment by Almesaody** [comment]
If running on replit: `kill 1` then start the bot again

**Comment by Almesaody** [comment]
Another problems

Unhandled promise rejection: Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
at WebSocketManager.createShards (/home/runner/Discord-Bot-1/node_modules/discord.js/src/client/websocket/WebSocketManager.js:250:15)
at async Client.login (/home/runner/Discord-Bot-1/node_modules/discord.js/src/client/Client.js:226:7) {
code: 'DisallowedIntents'
}
/home/runner/Discord-Bot-1/node_modules/discord.js/src/sharding/Shard.js:167
reject(new DiscordjsError(ErrorCodes.ShardingReadyTimeout, this.id));
^

Error [ShardingReadyTimeout]: Shard 0's Client took too long to become ready.
at Timeout.onTimeout (/home/runner/Discord-Bot-1/node_modules/discord.js/src/sharding/Shard.js:167:16)
at listOnTimeout (node:internal/timers:559:17)
at processTimers (node:internal/timers:502:7) {
code: 'ShardingReadyTimeout'

**Comment by Almesaody** [comment]
Please join our discord, there is also a advanced tutorial on how to set this up. This isn't a issue...
