### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Almesaody** [Almesaody/Discord-Bot#27]
Unhandled promise rejection: Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
at WebSocketManager.createShards (/home/runner/Discord-Bot-3/node_modules/discord.js/src/client/websocket/WebSocketManager.js:250:15)
at async Client.login (/home/runner/Discord-Bot-3/node_modules/discord.js/src/client/Client.js:226:7) {
code: 'DisallowedIntents'

**Comment by Almesaody** [comment]
May i again redirect you to the discord?
