### ISSUE TITLE
Music dont work anymore

### ISSUE THREAD

**Issue by Almesaody** [Almesaody/Discord-Bot#47]
Hey i wanted to hear music but this error pops up!

RangeError: No available nodes.
at new Player (/root/AsnaBOT/node_modules/erela.js/dist/structures/Player.js:102:19)
at Manager.create (/root/AsnaBOT/node_modules/erela.js/dist/structures/Manager.js:213:16)
at module.exports (/root/AsnaBOT/src/commands/music/play.js:23:32)
at Client.client.loadSubcommands (/root/AsnaBOT/src/handlers/functions/functions.js:88:130)
at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Almesaody** [comment]
![215271629-493b38ad-727c-466b-aa04-87d44bc38e5c](https://user-images.githubusercontent.com/120131207/232673049-fea8f2f8-cadc-4f30-88ca-0f68201a58e8.png)

**Comment by Almesaody** [comment]
Your lavalink is not available
