### ISSUE TITLE
🚨・Unhandled promise rejection

### ISSUE THREAD

**Issue by Almesaody** [Almesaody/Discord-Bot#51]
`🚨・Unhandled promise rejection Error Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted. Stack error Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted. at WebSocketManager.createShards (/home/runner/Critical/node_modules/discord.js/src/client/websocket/WebSocketManager.js:250:15) at async Client.login (/home/runner/Critical/node_modules/discord.js/src/client/Client.js:226:7)`

**Comment by Almesaody** [comment]
No need to post this 2 times
